services:
  database:
    image: postgis/postgis:15-master
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    healthcheck:
      test: "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  api: &api
    image: node:20-alpine
    working_dir: /api
    user: 1000:1000
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./api:/api
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - HOST=$HOST
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@database:5432/$POSTGRES_DB
      - NODE_ENV=development
      - JWT_SECRET=$JWT_SECRET
      - CLIENT_URL=$CLIENT_URL
      - MAIL_HOST=$MAIL_HOST
      - MAIL_PORT=$MAIL_PORT
      - MAIL_SECURE=$MAIL_SECURE
      - MAIL_FROM=$MAIL_FROM

  prisma-migrate:
    <<: *api
    restart: no
    command: >
      sh -c "npx prisma migrate dev && npx prisma -- db seed"
    ports: []

  prisma-studio:
    <<: *api
    command: npx prisma studio
    ports:
      - 5555:5555

  web-app:
    image: node:20-alpine
    working_dir: /web-app
    user: 1000:1000
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./web-app:/web-app
    depends_on:
      api:
        condition: service_started
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=$VITE_API_URL

  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
