FROM node:20-alpine AS base
WORKDIR /app

FROM base AS installer
WORKDIR /app
COPY package*.json ./
COPY .npm .npm
RUN npm run cache-install
COPY . .
RUN npm run cache-install && npm run typecheck && npm run build

FROM base AS runner
ENV NODE_ENV=production
ENV HOST=0.0.0.0
RUN addgroup --system --gid 1001 app && adduser --system --uid 1001 app
USER app
COPY --from=installer /app ./
CMD ["node", "dist/index.js"]